// <auto-generated />
namespace Helpdesk.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateBasicCustomerStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateBasicCustomerStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201704211230593_CreateBasicCustomerStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
